### PR TITLE
MNT: rerender

### LINKED ISSUE #24: @conda-forge-admin rerender
- [ ] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #24.

Here's a checklist to do before merging.
- [ ] Bump the build number if needed.

Fixes #24

### CODE REVIEW

**Comment by beckermr** [comment]
@conda-forge-admin rerender

**Comment by beckermr** [comment]
@conda-forge/proplot can you look at this?

xref: https://github.com/lukelbd/proplot/issues/309
xref: #23

**Comment by lukelbd** [comment]
Thanks for the help!

Does this update the conda recipe for all proplot versions or just 0.9.5? While we're at it we might as well update the recipe for all proplot versions (...assuming that's trivial to do?).

**Comment by lukelbd** [comment]
Or perhaps that's non-trivial... and what I *should* be doing is pinning every proplot version to the latest matplotlib version at the time of release, rather than using a naked `matplotlib` dependency?

**Comment by beckermr** [comment]
We can push a fix for all versions to our repodata patches. However, if proplot is using non-declared apis within matplotlib, a pin to a specific version (maybe major.minor) is not a horrible idea.

**Comment by lukelbd** [comment]
Cool -- then I assume that global fix would be outside of this PR? So, the best course would be to close this PR, edit conda's repodata patches (...don't really know what that means by the way 🤷‍♂️), then in future proplot releases I'll restrict the matplotlib version in `setup.cfg` rather than `meta.yml`?

The general rule proplot follows is "use matplotlib's public API whenever possible"... but occasionally it's not possible. Matplotlib also does not follow semantic versioning and occaionally deprecates the public API even in minor releases, and they can be fairly quick to remove deprecations, so restricting the mpl version is probably a good practice going forward.

**Comment by beckermr** [comment]
You have to do it in the meta.yaml too. Conda does not know about the setup.cfg. Plus there is the setuptools issue I identified. This PR needs to be merged.

**Comment by beckermr** [comment]
Thank you!

I'll make the patch to the repodata and tag you on the PR so you can see it.

**Comment by beckermr** [comment]
see here: https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/issues/201

PR to be made

**Pull request merged**
